### ISSUE TITLE
Add users route

### ISSUE THREAD

**Issue by jacepm** [ryama141/sample-login-backend#2]
# 🚀 Description
Users Account

### Schema

```typescript
{
  email: String; // this must be unique
  password: String; // this must be encrypted
}
```

#  📋 TASK
* [ ] **Generate users route**
* [ ] **Create users model**
* [ ] **POST /users**
    * [ ] check fields
        - [ ] if invalid return status 422 and error message
    * [ ] check password if valid password
        - [ ] if password not valid password return status 422 and error message " Password not valid!"
    * [ ] check password if match
        - [ ] if password not match return status 422 and error message " Password not match!"
    * [ ] encrypt password
    * [ ] create user from body with encrypted password
        - [ ] if create user failed return status 422 and error message
    * [ ] save user
        - [ ] if save user failed return status 422 and error message
    * [ ] user save successful return status 200 and success message
* [ ] **POST /users/login**
    * [ ] check fields
        - [ ] if invalid return status 422 and error message
    * [ ] check password if not correct
        - [ ] if password not correct return status 400 and error message " Password is not correct!"
    * [ ] user login
        - [ ] if user login failed return status 422 and error message
     * [ ] user login successful return status 200 and success message
* [ ] **GET /users**
    * [ ] find all user limit 100
        - [ ] if no user found return status 404 and error message "No users found!"
        - [ ] if user found return data: users, status 200 and success message
* [ ] **GET /users/:id**
    * [ ] find user by id
        - [ ] if no user found  return status 404 and error message "No user found!"
        - [ ] if user found return data: users, status 200 and success message
